"""course builder draft model

Adds the seven **mutable draft** authoring tables of the Course Builder
(``docs/specs/2026-06-08-course-builder-design.md``) — purely additive; nothing
in the immutable read path reads them. A draft is freely mutated in place while
authored, then compiled into the immutable content model on demand:

* ``draft_courses``         — the draft itself.
* ``draft_objectives``      — learning objectives authored for the course.
* ``draft_items``           — draft content items (lesson/lab/assessment/…).
* ``draft_item_objectives`` — join: which objectives an item covers.
* ``draft_dependencies``    — author/AI-proposed prerequisite edges.
* ``draft_rubric_results``  — stored rubric evaluations (RAG/score).
* ``draft_advisor_notes``   — AI/author notes on the draft or a target.

All seven are tenant-scoped, so each joins the fail-closed RLS regime. Per the
P-009 frozen-snapshot discipline this migration applies RLS **only to the seven
tables it creates**, via the per-table ``_enable_sql`` helper — it does NOT call
the live-list ``apply_rls`` (which, replayed from base, would try to enable RLS
on tables a later migration would otherwise add to the live list).

Round-trips: ``downgrade base && upgrade head`` clean on a fresh schema.

Revision ID: 194259011028
Revises: a8c0e2f4b6d8
Create Date: 2026-06-08 09:09:56.393569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from app.db.rls import _disable_sql, _enable_sql


# revision identifiers, used by Alembic.
revision: str = '194259011028'
down_revision: Union[str, Sequence[str], None] = 'a8c0e2f4b6d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Frozen snapshot: the tables THIS migration creates + RLS-protects. Hardcoded
# (not read from the live app.db.rls list) per P-009 so a from-base replay only
# ever touches tables that exist at this point in history.
_DRAFT_TABLES = (
    "draft_courses",
    "draft_objectives",
    "draft_items",
    "draft_item_objectives",
    "draft_dependencies",
    "draft_rubric_results",
    "draft_advisor_notes",
)

# The native PG ``assetkind`` enum already exists (created by the initial schema
# for the legacy model), so the ``draft_items.kind`` column must NOT re-emit a
# CREATE TYPE — use ``create_type=False``.
_assetkind = postgresql.ENUM(name="assetkind", create_type=False)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('draft_courses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('learner_profile', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('effort_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('target_weeks', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('curriculum_id', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_draft_courses_organization_id'), 'draft_courses', ['organization_id'], unique=False)
    op.create_table('draft_advisor_notes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('draft_course_id', sa.UUID(), nullable=False),
    sa.Column('target_kind', sa.String(length=16), nullable=True),
    sa.Column('target_ref', sa.String(length=64), nullable=True),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['draft_course_id'], ['draft_courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_draft_advisor_notes_draft_course_id'), 'draft_advisor_notes', ['draft_course_id'], unique=False)
    op.create_index(op.f('ix_draft_advisor_notes_organization_id'), 'draft_advisor_notes', ['organization_id'], unique=False)
    op.create_table('draft_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('draft_course_id', sa.UUID(), nullable=False),
    sa.Column('kind', _assetkind, nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('source_url', sa.String(length=1024), nullable=True),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('week_index', sa.Integer(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('estimated_minutes', sa.Integer(), nullable=True),
    sa.Column('ai_notes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['draft_course_id'], ['draft_courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_draft_items_draft_course_id'), 'draft_items', ['draft_course_id'], unique=False)
    op.create_index(op.f('ix_draft_items_organization_id'), 'draft_items', ['organization_id'], unique=False)
    op.create_table('draft_objectives',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('draft_course_id', sa.UUID(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('bloom_level', sa.String(length=16), nullable=False),
    sa.Column('key_skills', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('week_index', sa.Integer(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['draft_course_id'], ['draft_courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_draft_objectives_draft_course_id'), 'draft_objectives', ['draft_course_id'], unique=False)
    op.create_index(op.f('ix_draft_objectives_organization_id'), 'draft_objectives', ['organization_id'], unique=False)
    op.create_table('draft_rubric_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('draft_course_id', sa.UUID(), nullable=False),
    sa.Column('scope', sa.String(length=16), nullable=False),
    sa.Column('scope_ref', sa.String(length=64), nullable=True),
    sa.Column('rubric_key', sa.String(length=64), nullable=False),
    sa.Column('rag', sa.String(length=8), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_stale', sa.Boolean(), nullable=False),
    sa.Column('overridden', sa.Boolean(), nullable=False),
    sa.Column('override_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['draft_course_id'], ['draft_courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_draft_rubric_results_draft_course_id'), 'draft_rubric_results', ['draft_course_id'], unique=False)
    op.create_index(op.f('ix_draft_rubric_results_organization_id'), 'draft_rubric_results', ['organization_id'], unique=False)
    op.create_table('draft_dependencies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('draft_course_id', sa.UUID(), nullable=False),
    sa.Column('from_item_id', sa.UUID(), nullable=False),
    sa.Column('to_item_id', sa.UUID(), nullable=False),
    sa.Column('edge_type', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('accepted', sa.Boolean(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['draft_course_id'], ['draft_courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['from_item_id'], ['draft_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_item_id'], ['draft_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('draft_course_id', 'from_item_id', 'to_item_id', name='uq_draft_dependencies_course_from_to')
    )
    op.create_index(op.f('ix_draft_dependencies_draft_course_id'), 'draft_dependencies', ['draft_course_id'], unique=False)
    op.create_index(op.f('ix_draft_dependencies_from_item_id'), 'draft_dependencies', ['from_item_id'], unique=False)
    op.create_index(op.f('ix_draft_dependencies_to_item_id'), 'draft_dependencies', ['to_item_id'], unique=False)
    op.create_index(op.f('ix_draft_dependencies_organization_id'), 'draft_dependencies', ['organization_id'], unique=False)
    op.create_table('draft_item_objectives',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('draft_item_id', sa.UUID(), nullable=False),
    sa.Column('draft_objective_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['draft_item_id'], ['draft_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['draft_objective_id'], ['draft_objectives.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('draft_item_id', 'draft_objective_id', name='uq_draft_item_objectives_item_obj')
    )
    op.create_index(op.f('ix_draft_item_objectives_draft_item_id'), 'draft_item_objectives', ['draft_item_id'], unique=False)
    op.create_index(op.f('ix_draft_item_objectives_draft_objective_id'), 'draft_item_objectives', ['draft_objective_id'], unique=False)
    op.create_index(op.f('ix_draft_item_objectives_organization_id'), 'draft_item_objectives', ['organization_id'], unique=False)
    # ### end Alembic commands ###

    # Join the tenant-isolation RLS regime — frozen per-table snapshot (P-009).
    bind = op.get_bind()
    for table in _DRAFT_TABLES:
        for stmt in _enable_sql(table, "organization_id"):
            bind.execute(sa.text(stmt))


def downgrade() -> None:
    """Downgrade schema."""
    # Drop the policies first (they reference organization_id) — reverse order.
    bind = op.get_bind()
    for table in reversed(_DRAFT_TABLES):
        for stmt in _disable_sql(table):
            bind.execute(sa.text(stmt))

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_draft_item_objectives_organization_id'), table_name='draft_item_objectives')
    op.drop_index(op.f('ix_draft_item_objectives_draft_objective_id'), table_name='draft_item_objectives')
    op.drop_index(op.f('ix_draft_item_objectives_draft_item_id'), table_name='draft_item_objectives')
    op.drop_table('draft_item_objectives')
    op.drop_index(op.f('ix_draft_dependencies_organization_id'), table_name='draft_dependencies')
    op.drop_index(op.f('ix_draft_dependencies_to_item_id'), table_name='draft_dependencies', if_exists=True)
    op.drop_index(op.f('ix_draft_dependencies_from_item_id'), table_name='draft_dependencies', if_exists=True)
    op.drop_index(op.f('ix_draft_dependencies_draft_course_id'), table_name='draft_dependencies')
    op.drop_table('draft_dependencies')
    op.drop_index(op.f('ix_draft_rubric_results_organization_id'), table_name='draft_rubric_results')
    op.drop_index(op.f('ix_draft_rubric_results_draft_course_id'), table_name='draft_rubric_results')
    op.drop_table('draft_rubric_results')
    op.drop_index(op.f('ix_draft_objectives_organization_id'), table_name='draft_objectives')
    op.drop_index(op.f('ix_draft_objectives_draft_course_id'), table_name='draft_objectives')
    op.drop_table('draft_objectives')
    op.drop_index(op.f('ix_draft_items_organization_id'), table_name='draft_items')
    op.drop_index(op.f('ix_draft_items_draft_course_id'), table_name='draft_items')
    op.drop_table('draft_items')
    op.drop_index(op.f('ix_draft_advisor_notes_organization_id'), table_name='draft_advisor_notes')
    op.drop_index(op.f('ix_draft_advisor_notes_draft_course_id'), table_name='draft_advisor_notes')
    op.drop_table('draft_advisor_notes')
    op.drop_index(op.f('ix_draft_courses_organization_id'), table_name='draft_courses')
    op.drop_table('draft_courses')
    # ### end Alembic commands ###
