"""ccr target version

Revision ID: 50d0a66cf0d4
Revises: 895dc028e5f4
Create Date: 2026-06-03 16:13:49.672920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50d0a66cf0d4'
down_revision: Union[str, Sequence[str], None] = '895dc028e5f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('change_requests', sa.Column('target_version_id', sa.UUID(), nullable=True))
    op.create_foreign_key('change_requests_target_version_id_fkey', 'change_requests', 'versions', ['target_version_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('change_requests_target_version_id_fkey', 'change_requests', type_='foreignkey')
    op.drop_column('change_requests', 'target_version_id')
    # ### end Alembic commands ###
