"""ccr external link

Revision ID: 69b6ae8d3aba
Revises: 50d0a66cf0d4
Create Date: 2026-06-03 20:05:32.473307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69b6ae8d3aba'
down_revision: Union[str, Sequence[str], None] = '50d0a66cf0d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('change_requests', sa.Column('external_link', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('change_requests', 'external_link')
    # ### end Alembic commands ###
