"""unique approval per approver per ccr

Revision ID: 895dc028e5f4
Revises: 3fa58fc52cc5
Create Date: 2026-06-03 15:52:24.343528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '895dc028e5f4'
down_revision: Union[str, Sequence[str], None] = '3fa58fc52cc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_approval_ccr_approver', 'approvals', ['ccr_id', 'approver_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_approval_ccr_approver', 'approvals', type_='unique')
    # ### end Alembic commands ###
